pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'pawankavinda/portfolio'
    }

    stages {
        stage('Checkout') {
            steps {
               
                git url: 'https://github.com/pawan-kavinda/Portfolio.git', branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                   
                    dockerImage = docker.build("${DOCKER_IMAGE}:latest", './frontend')
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('', '8c3e03d9-a7e1-428b-9947-2edfd5f9ade6') {
                        dockerImage.push()
                    }
                }
            }
        }

        stage('Run Container') {
            steps {
                bat '''
                docker stop portfolio || echo Container not running
                docker rm portfolio || echo Container not removed
                docker run -d --name portfolio -p 80:80 %DOCKER_IMAGE%:latest
                '''
            }
        }
    }
}
